config/routes.rb
Rails.application.routes.draw do

  resources :messages
  devise_for :users
    root to: 'pages#home'
  get "/team" => "pages#team"
  get "/contact" => "pages#contact"
  get "/profil" => "pages#profil"
  resources :docs
  resources :profiles
  resources :contenues
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contenue.rb
class Contenue < ApplicationRecord
  
   validates :title, presence: true
  validates :url, presence: true
  validates :abstract, presence: true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
   validates :name, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
end

app/models/docu.rb
class Docu < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord

   validates :body, presence: true
  validates :topic, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contenues_controller.rb
class ContenuesController < ApplicationController

    def index

      @contenues = Contenue.all
      
  end

  def show

    @contenue = Contenue.find(params[:id])

  end

  def new
    @contenue = Contenue.new
  end
  def create
@contenue = Contenue.new(product_params)
   if @contenue.save
    redirect_to contenues_path
   else
     render :new
   end
  end

  def edit
    @contenue = Contenue.find(params[:id])

  end

    private
  def product_params
    params.require(:contenue).permit(:title, :url, :abstract)
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  def new
    @doc = Doc.new
  end
  def create
@doc = Doc.new(doc_params)
   if @doc.save
    redirect_to docs_path
   else
     render :new
   end
  end
   def show
    @doc= Doc.find(params[:id])
  end
     def index
    @docs = Doc.all
  end



  private

  def doc_params
    params.require(:doc).permit(:name, :url, :abstract)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    if params[:topic]
      @messages = Message.where(topic: params[:topic])
      else
      @messages = Message.all
      end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body, :name, :topic)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

   def home
    @contenuee= Contenue.all
     @doc= Doc.all.reverse.take(5)
  end
  def team
    # ...
  end
  def contact
    # ...
  end
  def profil
    @user= User.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
   @profile = Profile.find_by user_id: current_user.id
   @attributes = Profile.attribute_names - %w(id user_id created_at updated_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contenues_helper.rb
module ContenuesHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/contenues/_form.html.erb
 <%= simple_form_for @contenue do |f| %>
      <%= f.input :title, placeholder: "Name", label: "Title", class: "text-left" %>
      <%= f.input :abstract, placeholder: "Short resume", label: "abstract" %>
      <%= f.input :url, as: :url, label: "link", input_html: { value: "http://" } %>
      <%= f.button :submit, "Add", class: "btn btn-primary" %>
  <% end %>

app/views/contenues/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1 class="text-center"> All Contents </h1>
      <% @contenues.each do |contenue| %>
      <div class="product">

 <%= link_to contenue.url do %>

         <div class='product-body'>
            <h3 class="ttext"><%= contenue.title %></h3>
            <p class="ttext"><%= contenue.abstract %></p>
           <% end %> 
          </div>

        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contenues/new.html.erb
<div class=" text-left container ">
<div class="  col-xs-5 col-xs-offset-4">
  <h1> NEW Content</h1>

<%= render "form" %>
</div>
</div>

app/views/docs/_form.html.erb
 <%= simple_form_for @doc do |f| %>
      <%= f.input :name, placeholder: "Name", label: "Name doc?" %>
<%= image_tag("gifdoc.gif", width:"700px") %>
      <%= f.input :url, as: :url, label: "share public link", input_html: { value: "https://" } %>
      <%= f.input :abstract, as: :text, placeholder: "long resume", label: "description" %>
      <%= f.button :submit, "Add", class: "btn btn-primary" %>
  <% end %>

app/views/docs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1 class="text-center"> All Documents </h1>
      <% @docs.each do |doc| %>
      <div class="doc product">

 <%= link_to doc_path(doc) do %>
         <div class='product-body'>
           <div class='product-body col-xs-2'><%=image_tag("doc.png")%> <br><br></div>
            <h3 class="ttext"><%= doc.name %></h3>
            <p class="ttext"><%= doc.abstract %></p>
           <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/docs/new.html.erb
<div class=" text-center container">

  <h1> NEW Doc</h1>

<%= render "form" %>
</div>

app/views/docs/show.html.erb
<div class="container text-center">
    <h1><%= @doc.name %></h1>
    <p><%= @doc.abstract %></p>
    <div class="container"><iframe src="<%= @doc.url %>" width="1200" height="1200"></iframe> </div> <br>
   <%= link_to "open in Google doc", @doc.url, class:"navbar-wagon-item navbar-wagon-button btn btn-primary"  %><br><br>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>PLATFORM</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>
      <style type="text/css">
    a {text-decoration: none;}
   a:hover {text-decoration: none;}
  </style>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= render "shared/analytics" %>
    
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
     <%= f.input :topic %>
     <%= f.input :name %>
    <%= f.input :body %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>

      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.topic %></td>
        <td><%= message.name %></td>
        <td><%= link_to 'Show', message %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<div class="container">
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>
</div>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @message.topic %>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.name %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/pages/contact.html.erb
contact

app/views/pages/home.html.erb
<%= render "shared/bannerhome" %>
<br>
<br>
<br>
<style type="text/css">
    .content-footer a {text-decoration: none;color:white;}
   .content-footer:hover a {text-decoration: none;color:white;}
  </style>
<%= render "shared/contenue" %>
<br>
<br>
<br>
<br>
<%= render "shared/chat" %>

app/views/pages/profil.html.erb
<div class="container ">
  <br><br><br><br>
  <div class=" col-md-offset-4">
  <figure class="snip1376">
  <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/331810/sample17.jpg" alt="sample17" />
  <figcaption>
    <h2><%= @user.name %></h2>
    <p>I'm looking for something that can deliver a 50-pound payload of snow on a small feminine target. Can you suggest something? Hello? </p>
    
  </figcaption>
</figure>
</div>
  </div>

app/views/pages/team.html.erb
team

app/views/profiles/edit.html.erb
<%= form_for @profile do |f| %>
    <% @attributes.each do |attr| %>
       <%= f.text_field attr.to_sym %>
    <% end %>
<% end %>

app/views/shared/_bannerhome.html.erb
<% if user_signed_in? %>
    <div class="container">

      <h1 class="text-center"></h1>





<% else %>
  <div class="banner" > 
    <div class="banner-content">
      <h1>Open CO2</h1><br>
      <h2>Open Scientists community talked about Environment </h2><br><br><br><br><br><br><br><br>
      <%= link_to "GET IT", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>

app/views/shared/_chat.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Community</h1>
  </div>
</div>
<div class="jumbotron container">
  <div class="container">
    <h1 class="display-3">Documents</h1><br>
    <p class="lead">
      <% @doc.each do |doc| %>
      <tr>
         <%=image_tag("icondoc.png")%>
         <%= link_to doc.name, doc_path(doc), class: "card-product " %><br>


      </tr>
    <% end %>
      <br><br>
<%= link_to "All Documents", docs_path, class:"text-right pull-xs-right" %>

    </p>
  </div>
</div>
<div class="jumbotron container">
  <div class="container">
	<div class="loading col-md-4">
		  <div class="dot one"></div>
		  <div class="dot two"></div>
		  <div class="dot three"></div>
		  <div class="dot four"></div>
	</div>
    <div class=" col-md-8 text-center"> <br>
      <h3 class="text-center">  Join our Community in slack </h3><br><br><br>
       <p class="text-center col-md-2"><br><br></p>
      <p class="text-center col-md-8">   A messaging app for teams who are changing the world. <br><br>We using Slack to make their working lives simpler, more pleasant, and more productive.</p><br><br><br>
       <p class="text-center col-md-2"><br><br></p>
       <p class="text-center col-md-4"><br><br></p><br><br><br><br>
    <br><br>  <a class="typeform-share btn btn-lg slack-btn  text-center col-md-5 " href="https://cyrilfert.typeform.com/to/b0ampv" data-mode="1" target="_blank">Join US</a>
<script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'share.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}id=id+'_';if(!gi.call(d,id)){qs=ce.call(d,'link');qs.rel='stylesheet';qs.id=id;qs.href=b+'share-button.css';s=gt.call(d,'head')[0];s.appendChild(qs,s)}})()</script>

	</div>
      </div>
</div>

app/views/shared/_contenue.html.erb
<div class="container cont">
<div class="row">
    <div class="col-lg-4">
       <div class="card card-outline-danger text-xs-center card-content">
      <div class="card-block">
        <blockquote class="card-blockquote">
          <p><%= @contenuee.find(1).title%></p>
          <footer class="content-footer"><%= link_to @contenuee.find(1).url, @contenuee.find(1).url%></footer>
        </blockquote>
  </div>
</div>
    </div>
    <div class="col-lg-4">
       <div class="card card-inverse card-danger text-xs-center card-contentd">
  <div class="card-block">
    <blockquote class="card-blockquote">
      <p>Open comminity about ennivonnement.</p>
      <footer class="content-footer">Made with ❤ <cite title="Source Title">for save the world</cite></footer>
    </blockquote>
  </div>
</div>
    </div>
    <div class="col-lg-4">
          <div class="card card-outline-danger text-xs-center card-content">
      <div class="card-block">
        <blockquote class="card-blockquote">
         <p><%= @contenuee.find(2).title%></p>
          <footer class="content-footer"><%= link_to @contenuee.find(1).url, @contenuee.find(1).url%></footer>
        </blockquote>
  </div>
</div>
    </div>
  <div class="col-lg-4">
       <div class="card card-outline-danger text-xs-center card-content">
      <div class="card-block">
        <blockquote class="card-blockquote">
         <p><%= @contenuee.find(3).title%></p>
          <footer class="content-footer"><%= link_to @contenuee.find(1).url, @contenuee.find(1).url%></footer>
        </blockquote>
  </div>
</div>
    </div>
  <div class="col-lg-4">
      <div class="embed-responsive embed-responsive-16by9 card-content">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/rUO8bdrXghs" allowfullscreen></iframe>
</div>
    </div>
  <div class="col-lg-4">
       <div class="card card-outline-danger text-xs-center card-content">
      <div class="card-block">
        <blockquote class="card-blockquote">
         <p><%= @contenuee.find(4).title%></p>
          <footer class="content-footer"><%= link_to @contenuee.find(1).url, @contenuee.find(1).url%></footer>
        </blockquote>
  </div>
</div>
    </div>
  </div>
</div>
<%= link_to "All content", contenues_path, class:"text-right pull-xs-right" %>
</div>

app/views/shared/_footer.html.erb
<footer>

</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
   <%= image_tag "logo.png" %>   <h13> </h13>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <!-- Text link -->

      <%= link_to "All DOC", docs_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "Add content", new_contenue_path, class: "navbar-wagon-item navbar-wagon-link" %>

   <!-- <%= link_to "Profil", new_profile_path, class: "navbar-wagon-item navbar-wagon-link" %> -->
      <% if user_signed_in? %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

          <li> <%= link_to "log out", destroy_user_session_path, method: :delete %> </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->

    <%= link_to "ADD Doc", new_doc_path, class:"navbar-wagon-item navbar-wagon-button btn"  %>

      <% else %>
      <%= link_to "Sign UP", new_user_registration_path, class:"navbar-wagon-item navbar-wagon-button btn" %>
      <%= link_to "Log in", new_user_session_path, class:"navbar-wagon-item navbar-wagon-button btn" %>
  <% end %>





  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

</div>